# Generated by Django 5.1.5 on 2025-03-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
