"""
Django settings for myFinPlanner project.

Generated by 'django-admin startproject' using Django 5.1.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k&33l24mir!g^rpei#+4ig(w*(*k&em#ohuzp2&krk6l%qp-19'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#IP del servidow AWS 
ALLOWED_HOSTS = ['3.84.44.51']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'finances.apps.FinancesConfig',
    'investments.apps.InvestmentsConfig',
    'accounts.apps.AccountsConfig',
    'analytics.apps.AnalyticsConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORRECCIÓN: usa "myFinPlanner" (con F mayúscula) para que coincida con el nombre de la carpeta del proyecto
ROOT_URLCONF = 'myFinPlanner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

# CORRECCIÓN: Actualiza WSGI para usar el nombre correcto del módulo
WSGI_APPLICATION = 'myFinPlanner.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Apunta a la carpeta principal "static"
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Carpeta donde se recolectarán los archivos estáticos en producción

# Media files (para informes, imágenes, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/finances/'  # Cambia esto a la URL de tu dashboard o página principal después de iniciar sesión
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Configuración de mensajes
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Configuración de correo electrónico (para desarrollo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# API Keys
FINNHUB_API_KEY = "cvbnah9r01qob7uep660cvbnah9r01qob7uep66g"

AUTH_USER_MODEL = 'accounts.CustomUser'

# Configuración de correo electrónico (para desarrollo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'

# indica a Django que la URL de login es /login/
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/' 

