# Generated by Django 5.1.5 on 2025-03-17 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Crypto', 'Crypto')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.investmentsymbol'),
        ),
    ]
