# Generated by Django 5.1.5 on 2025-03-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_investmentsymbol_remove_investment_investment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsymbol',
            name='name',
            field=models.CharField(default='unkown', max_length=100),
        ),
    ]
