# Generated by Django 5.1.5 on 2025-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_investment_user_alter_investmentsymbol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
