# Generated by Django 5.1.5 on 2025-03-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_investment_user_alter_investmentsymbol_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvestmentSymbol',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
